global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-metrics:9121']
  - job_name: 'rlaas'
    static_configs:
      - targets: ['rlaas:8080']