global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-metrics:9121']
  - job_name: 'rlaas'
    static_configs:
      - targets: ['rlaas:8080']